// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// pyrun
void pyrun(std::string command);
RcppExport SEXP Rpyplot_pyrun(SEXP commandSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type command(commandSEXP);
    pyrun(command);
    return R_NilValue;
END_RCPP
}
// initialize_python
void initialize_python();
RcppExport SEXP Rpyplot_initialize_python() {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    initialize_python();
    return R_NilValue;
END_RCPP
}
// finalize_python
void finalize_python();
RcppExport SEXP Rpyplot_finalize_python() {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    finalize_python();
    return R_NilValue;
END_RCPP
}
// numvec_to_python
void numvec_to_python(std::string name, NumericVector x);
RcppExport SEXP Rpyplot_numvec_to_python(SEXP nameSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    numvec_to_python(name, x);
    return R_NilValue;
END_RCPP
}
// charvec_to_python
void charvec_to_python(std::string name, std::vector< std::string > strings);
RcppExport SEXP Rpyplot_charvec_to_python(SEXP nameSEXP, SEXP stringsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    Rcpp::traits::input_parameter< std::vector< std::string > >::type strings(stringsSEXP);
    charvec_to_python(name, strings);
    return R_NilValue;
END_RCPP
}
// numvec_to_R
NumericVector numvec_to_R(std::string name);
RcppExport SEXP Rpyplot_numvec_to_R(SEXP nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    __result = Rcpp::wrap(numvec_to_R(name));
    return __result;
END_RCPP
}
// charvec_to_R
std::vector<std::string> charvec_to_R(std::string name);
RcppExport SEXP Rpyplot_charvec_to_R(SEXP nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    __result = Rcpp::wrap(charvec_to_R(name));
    return __result;
END_RCPP
}
// num_to_dict
void num_to_dict(NumericVector x, std::string name, std::string dictname);
RcppExport SEXP Rpyplot_num_to_dict(SEXP xSEXP, SEXP nameSEXP, SEXP dictnameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    Rcpp::traits::input_parameter< std::string >::type dictname(dictnameSEXP);
    num_to_dict(x, name, dictname);
    return R_NilValue;
END_RCPP
}
// char_to_dict
void char_to_dict(std::vector<std::string> x, std::string name, std::string dictname);
RcppExport SEXP Rpyplot_char_to_dict(SEXP xSEXP, SEXP nameSEXP, SEXP dictnameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    Rcpp::traits::input_parameter< std::string >::type dictname(dictnameSEXP);
    char_to_dict(x, name, dictname);
    return R_NilValue;
END_RCPP
}
