// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// pyrun
void pyrun(std::string command);
RcppExport SEXP Rpyplot_pyrun(SEXP commandSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type command(commandSEXP);
    pyrun(command);
    return R_NilValue;
END_RCPP
}
// initialize_python
void initialize_python();
RcppExport SEXP Rpyplot_initialize_python() {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    initialize_python();
    return R_NilValue;
END_RCPP
}
// finalize_python
void finalize_python();
RcppExport SEXP Rpyplot_finalize_python() {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    finalize_python();
    return R_NilValue;
END_RCPP
}
// numvec_to_python
void numvec_to_python(std::string name, NumericVector x);
RcppExport SEXP Rpyplot_numvec_to_python(SEXP nameSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    numvec_to_python(name, x);
    return R_NilValue;
END_RCPP
}
