# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pyrun <- function(command) {
    invisible(.Call('Rpyplot_pyrun', PACKAGE = 'Rpyplot', command))
}

initialize_python <- function() {
    invisible(.Call('Rpyplot_initialize_python', PACKAGE = 'Rpyplot'))
}

finalize_python <- function() {
    invisible(.Call('Rpyplot_finalize_python', PACKAGE = 'Rpyplot'))
}

numvec_to_python <- function(name, x) {
    invisible(.Call('Rpyplot_numvec_to_python', PACKAGE = 'Rpyplot', name, x))
}

