# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Run python code
#'
#' Runs Python code in namespace __main__ . 
#' 
#' @param command Python code to execute as string
#' @examples
#' pyrun("print range(5)")
#' @export
pyrun <- function(command) {
    invisible(.Call('Rpyplot_pyrun', PACKAGE = 'Rpyplot', command))
}

initialize_python <- function() {
    invisible(.Call('Rpyplot_initialize_python', PACKAGE = 'Rpyplot'))
}

finalize_python <- function() {
    invisible(.Call('Rpyplot_finalize_python', PACKAGE = 'Rpyplot'))
}

#' Push data to python __main__ namespace
#' 
#' @param name Python variable name as string
#' @param x Numeric vector to copy to Python
#' 
#' @examples
#' numvec_to_python("l", 1:10)
#' pyrun("print l")
#' 
#' @export
numvec_to_python <- function(name, x) {
    invisible(.Call('Rpyplot_numvec_to_python', PACKAGE = 'Rpyplot', name, x))
}

